### ISSUE TITLE
Trigger JS events for TopBar forms 

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-top-bar#85]
Maybe just trigger the standard MC4WP events, and set the form name to Top-Bar?
https://www.mc4wp.com/kb/javascript-form-events/

Requested here: https://wordpress.org/support/topic/javascript-when-submitting-topbar/

**Comment by dannyvankooten** [comment]
I'm trying to minimise reliance on the custom JS API that is shipped with Mailchimp for WordPress core as it's only used by a very small subset of our users yet still needs to be loaded for all of them (because we can't tell if someone is using it before loading it) so have instead added a sample snippet for this that uses plain JavaScript.
