### ISSUE TITLE
Prevent Cumulative Layout Shift warning in Google Page Speed test

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-top-bar#90]
![image](https://user-images.githubusercontent.com/9718808/104871746-747c8100-597e-11eb-8b82-eb882f525502.png)

According to the user report this can be solved by simply adding a margin to the topbar for the height of the topbar?

Reported: https://wordpress.org/support/topic/cls-issue-solution-potential/

**Comment by udiudiudiudi** [comment]
This is a reference to another topbar plugin that solved this CLS issue
https://wordpress.org/support/topic/the-plugin-causes-high-cumulative-layout-shift-is-there-a-solution/

**Comment by udiudiudiudi** [comment]
HI, any update on this issue please?

**Comment by dannyvankooten** [comment]
With a dynamic top bar plugin (meaning: height is unknown because the bar's content can be anything) is it straight up impossible to prevent cumulative layout shift as some heights have to be calculated after things are rendered (and styled).

Therefore the best way to prevent CLS altogether (if it matters for your website) is to use a bottom bar instead of a top bar.
